apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  rabbitmq_host: rabbitmq.dev.svc
  rabbitmq_port: "5672"
  database_driver: com.mysql.cj.jdbc.Driver
  database_url: 'jdbc:mysql://db.dev.svc:3306/worldmessages?createDatabaseIfNotExist=true'
  database_name: worldmessages
  database_host: '%'
  