apiVersion: apps/v1
kind: Deployment
metadata:
  name: spain-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: spain-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spain-service
    spec:
      containers:
      - name: spain-service
        image: spain-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          timeoutSeconds: 7
          periodSeconds: 10
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 45
          timeoutSeconds: 7
          periodSeconds: 15
          failureThreshold: 3
        env:
        - name: CONFIG_FOLDER
          value: /workspace/config
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq_host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq_port
        - name: SECRETS_RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: rabbitmq_user
        - name: SECRETS_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: rabbitmq_password
        volumeMounts:
          - mountPath: /workspace/config
            name: config-volume
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: spain-service
  namespace: dev
  labels:
    app: spain-service
spec:
  type: NodePort
  ports:
    - port: 8082
      name: port-8082
  selector:
    app: spain-service
